hospital_ratings/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('detail/<str:id>', views.detail, name='detail')
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

class QueryForm(forms.Form):
    #Hospital name
    name = forms.CharField(max_length=50, required=False)
    
    #Hospital location
    address = forms.CharField(max_length=80, required=False)
    city = forms.CharField(max_length=15, required=False)
    zip = forms.CharField(max_length=5, required=False)
    county = forms.CharField(max_length=15, required=False)
    state = forms.CharField(max_length=15, required=False)
    
    #Hospital type
    type = forms.CharField(max_length=50, required=False)

    #Emergency Service
    erYes = forms.BooleanField(required=False, initial=True)
    erNo = forms.BooleanField(required=False, initial=True)
    
    #Ownership
    government = forms.BooleanField(required=False, initial=True)
    nonprofit = forms.BooleanField(required=False, initial=True)
    physician = forms.BooleanField(required=False, initial=True)
    proprietary = forms.BooleanField(required=False, initial=True)
    tribal = forms.BooleanField(required=False, initial=True)
    
    #OveralRatings
    rate1 = forms.BooleanField(required=False, initial=True)
    rate2 = forms.BooleanField(required=False, initial=True)
    rate3 = forms.BooleanField(required=False, initial=True)
    rate4 = forms.BooleanField(required=False, initial=True)
    rate5 = forms.BooleanField(required=False, initial=True)
    ratena = forms.BooleanField(required=False, initial=True)
    
    #National Comparisons
    mortalityBelow = forms.BooleanField(required=False, initial=True)
    mortalityAbove = forms.BooleanField(required=False, initial=True)
    mortalityEqual = forms.BooleanField(required=False, initial=True)
    mortalityNa = forms.BooleanField(required=False, initial=True)
    
    safetyBelow = forms.BooleanField(required=False, initial=True)
    safetyAbove = forms.BooleanField(required=False, initial=True)
    safetyEqual = forms.BooleanField(required=False, initial=True)
    safetyNa = forms.BooleanField(required=False, initial=True)
    
    readmissionBelow = forms.BooleanField(required=False, initial=True)
    readmissionAbove = forms.BooleanField(required=False, initial=True)
    readmissionEqual = forms.BooleanField(required=False, initial=True)
    readmissionNa = forms.BooleanField(required=False, initial=True)
    
    patientExperienceBelow = forms.BooleanField(required=False, initial=True)
    patientExperienceAbove = forms.BooleanField(required=False, initial=True)
    patientExperienceEqual = forms.BooleanField(required=False, initial=True)
    patientExperienceNa = forms.BooleanField(required=False, initial=True)
    
    effectivenessBelow = forms.BooleanField(required=False, initial=True)
    effectivenessAbove = forms.BooleanField(required=False, initial=True)
    effectivenessEqual = forms.BooleanField(required=False, initial=True)
    effectivenessNa = forms.BooleanField(required=False, initial=True)
    
    timelinessBelow = forms.BooleanField(required=False, initial=True)
    timelinessAbove = forms.BooleanField(required=False, initial=True)
    timelinessEqual = forms.BooleanField(required=False, initial=True)
    timelinessNa = forms.BooleanField(required=False, initial=True)
    
    medicalImagingBelow = forms.BooleanField(required=False, initial=True)
    medicalImagingAbove = forms.BooleanField(required=False, initial=True)
    medicalImagingEqual = forms.BooleanField(required=False, initial=True)
    medicalImagingNa = forms.BooleanField(required=False, initial=True)

    SORT_BY_CHOICES = [
        ('?name', 'Name'),
        ('?overallRating', 'Rating')
    ]
    sortBy = forms.CharField(label='Sort By', widget=forms.Select(choices=SORT_BY_CHOICES))

    SORT_OPTIONS=[
        ('ASC','Ascending'),
        ('DESC','Descending')
    ]

    sortOptions = forms.ChoiceField(label='Sort Options', initial=('ASC','Ascending'), choices=SORT_OPTIONS, widget=forms.RadioSelect)

main/views.py
from django.shortcuts import render
from .forms import QueryForm
from rdflib import Graph
from SPARQLWrapper import SPARQLWrapper, JSON, N3
from pprint import pprint
import ssl
from pymantic import sparql as sparql
from .util import *

def home(request):
    return render(request, 'main/home.html')

def search(request):
    if request.method == 'POST':
        form = QueryForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
        name,address,city,zip,county,\
        state,type,er,ownership,rating,\
        mortality,safety,readmission, \
        patientExperience,effectiveness,\
        timeliness,medicalImaging = cleaned_form_to_lists(form.cleaned_data)
        query = '''
            select *
            where {?hospital <ex:name> ?name.
                   ?hospital <ex:overallRating> ?overallRating.
                   ?hospital <ex:hospitalType> ?hospitalType.
                   ?hospital <ex:phoneNumber> ?phoneNumber.
                   ?hospital <ex:address> ?address.
                   ?hospital <ex:city> ?city.
                   ?hospital <ex:postalCode> ?postalCode.
                   ?hospital <ex:county> ?county.
                   ?hospital <ex:emergencyService> ?emergencyService.
                   ?hospital <ex:hospitalType> ?hospitalType.
                   ?hospital <ex:mortalityComparison> ?mortalityComparison.
                   ?hospital <ex:ownership> ?ownership.
                   ?hospital <ex:state> ?state.
                   ?hospital <ex:effectiveness> ?effectiveness.
                   ?hospital <ex:medicalImaging> ?medicalImaging.
                   ?hospital <ex:readmission> ?readmission.
                   ?hospital <ex:safetyCare> ?safetyCare.
                   ?hospital <ex:timeliness> ?timeliness.
                  FILTER ( 
                  (regex(?name,".*'''+ name +'''.*","i")) 
                  && (regex(?hospitalType,".*'''+ type +'''.*","i")) 
                  && (regex(?address,".*'''+ address +'''.*","i")) 
                  && (regex(?city,".*'''+ city +'''.*","i"))
                  && (regex(?state,".*'''+ state +'''.*","i"))
                  && (regex(?overallRating,"'''+ rating +'''","i"))
                  && (regex(?postalCode,".*'''+ zip +'''.*","i"))
                  && (regex(?county,".*'''+ county +'''.*","i"))
                  && (regex(?emergencyService,"'''+ er +'''","i"))
                  && (regex(?mortalityComparison,"'''+ mortality +'''","i"))
                  && (regex(?ownership,"'''+ ownership +'''","i"))
                  && (regex(?effectiveness,".*'''+ effectiveness +'''.*","i"))
                  && (regex(?medicalImaging,".*'''+ medicalImaging +'''.*","i"))
                  && (regex(?readmission,".*'''+ readmission +'''.*","i"))
                  && (regex(?safetyCare,".*'''+ safety +'''.*","i"))
                  && (regex(?timeliness,".*'''+ timeliness +'''.*","i"))
                  ).
            }
            ORDER BY ''' + form.cleaned_data['sortOptions'] + '''(''' + form.cleaned_data['sortBy'] + ''')''''''
        '''

        print(query)
        sparql = SPARQLWrapper('http://192.168.78.188:9999/blazegraph/sparql')
        sparql.setQuery(
        query
        )

        sparql.setReturnFormat(JSON)
        qres = sparql.query().convert()
    else:
        form = QueryForm()
        qres = {'head': {'vars': ['hospital', 'name', 'overallRating', 'hospitalType', 'address', 'emergencyService']}, 'results': {'bindings': []}}
    
    return render(request, 'search.html', {'qres' : qres, 'form':form})

def detail(request, id):
    sparql = SPARQLWrapper('http://192.168.78.188:9999/blazegraph/sparql')
    sparql = SPARQLWrapper('http://192.168.78.188:9999/blazegraph/sparql')
    query = '''
    select *
    where {?hospital <ex:name> ?name.
           ?hospital <ex:overallRating> ?overallRating.
           ?hospital <ex:hospitalType> ?hospitalType.
           ?hospital <ex:phoneNumber> ?phoneNumber.
           ?hospital <ex:address> ?address.
           ?hospital <ex:city> ?city.
           ?hospital <ex:postalCode> ?postalCode.
           ?hospital <ex:county> ?county.
           ?hospital <ex:emergencyService> ?emergencyService.
           ?hospital <ex:hospitalType> ?hospitalType.
           ?hospital <ex:mortalityComparison> ?mortalityComparison.
           ?hospital <ex:ownership> ?ownership.
           ?hospital <ex:state> ?state.
           ?hospital <ex:effectiveness> ?effectiveness.
           ?hospital <ex:medicalImaging> ?medicalImaging.
           ?hospital <ex:readmission> ?readmission.
           ?hospital <ex:safetyCare> ?safetyCare.
           ?hospital <ex:timeliness> ?timeliness.
          FILTER ( ?hospital = <'''+ id +'''> ).
    }
    '''
    sparql.setQuery(query)

    sparql.setReturnFormat(JSON)
    qres = sparql.query().convert()
    
    hospital = qres['results']['bindings'][0]
    
    ssl._create_default_https_context = ssl._create_unverified_context

    sparql = SPARQLWrapper('https://dbpedia.org/sparql')
    query = '''
    select *
    where {?county dbp:county ?countyName.
           ?county dbp:state ?stateName.
           ?county rdf:type dbo:Region.
           ?county dbo:abstract ?abstract.
          FILTER (
          regex(?countyName, "'''+hospital['county']['value']+'''.*","i")
          && regex(?stateName, "'''+abbreviation_to_name(hospital['state']['value'])+'''.*","i")
          && lang(?abstract) = 'en'
          ).
    }
    '''
    sparql.setQuery(query)

    sparql.setReturnFormat(JSON)
    countyDetail = sparql.query().convert()

    city = hospital['city']['value']
    sparql = SPARQLWrapper('https://dbpedia.org/sparql')
    query = '''
    select distinct ?city ?name
            where {?county dbp:city ?city .
           ?city dbp:name ?name.
           FILTER regex(?name, "'''+city+'''", "i").
            }
    LIMIT 1
    '''
    sparql.setQuery(query)

    sparql.setReturnFormat(JSON)
    countyURI = sparql.query().convert()

    name = hospital['name']['value']
    sparql = SPARQLWrapper('https://dbpedia.org/sparql')
    query = '''
    select distinct ?hospital ?name ?bedCount ?abstract
            where {?hospital rdf:type dbo:Hospital.
           ?hospital dbp:name ?name.
           ?hospital dbo:bedCount ?bedCount .
           ?hospital dbo:abstract ?abstract .
           FILTER regex(?name, "'''+name+'''", "i").
            }
    LIMIT 1
    '''
    sparql.setQuery(query)

    sparql.setReturnFormat(JSON)
    nameURI = sparql.query().convert()

    state = hospital['state']['value']
    sparql = SPARQLWrapper('https://dbpedia.org/sparql')
    stateName = abbreviation_to_name(state)
    print(stateName)
    query = '''
    select distinct ?state ?name
            where {?county dbo:state ?state .
           ?state dbp:name ?name.
           FILTER regex(?name, "'''+stateName+'''", "i").
            }
    LIMIT 1
    '''
    sparql.setQuery(query)

    sparql.setReturnFormat(JSON)
    stateURI = sparql.query().convert()



    return render(request, 'detail.html', {
        'qres' : qres,
        'countyDetail' : countyDetail,
        'countyURI' : countyURI,
        'nameURI' : nameURI,
        'stateURI' : stateURI
        })

main/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SemWeb</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}
">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <br>
    <div class="card">
        <h6 class="card-header d-flex justify-content-center bg bg-info">
            Detail Hospital
        </h6>
        <div class="card-body">
            {% for hospital in qres.results.bindings %}
            <h1><p>{% for nameURI in nameURI.results.bindings %}
            <a href=" {{ nameURI.hospital.value }} ">
            {% endfor %}
            {{ hospital.name.value }}</a></p></h1>

            {% for nameURI in nameURI.results.bindings %}
            <b>Abstract:</b> {{ nameURI.abstract.value }}
            {% endfor %}
            <br>

            <b><br>The hospital is located at address :</b>
            <p>{{ hospital.address.value }}</p>

            <b><br>It is located at county:</b>
                {% for countyLink in countyURI.results.bindings %}
                <a href="{{ countyLink.city.value }} ">
                {% endfor %}
                {{ hospital.county.value }}</a>


            <b><br>It is located at state:</b>
                {% for stateLink in stateURI.results.bindings %}
                <a href=" {{ stateLink.state.value }} ">
                {% endfor %}
                {{ hospital.state.value }} </a><br>


            <b><br>The hospital is owned by :</b>
            <p>{{ hospital.ownership.value }}</p>

            <b><br>The hospital rating is :</b>
            <p>{{ hospital.overallRating.value }}</p>

            <b><br>Available for ER? :</b>
            <p>{{ hospital.emergencyService.value }}</p>

            <b><br>Statistic compared to national value:</b>
            <b><p>Mortality rate :</b> {{ hospital.mortalityComparison.value }}</p>
            <b> <p>Efficient use of medical imaging :</b> {{ hospital.medicalImaging.value }}</p>
            <b><p>Safety of Care :</b> {{ hospital.safetyCare.value }}</p>
            <b><p>Effectiveness of Care :</b> {{ hospital.effectiveness.value }}</p>
            <b><p>Readmission rate :</b> {{ hospital.readmission.value }}</p>
            <b> <p>Timeliness of Care : </b>{{ hospital.timeliness.value }}</p>

            {% endfor %}
            

            {% for nameURI in nameURI.results.bindings %}
            <b>The hospital capacity is: </b>
            <p>{{ nameURI.bedCount.value }} beds
            {% endfor %}

        </div>
    </div>
</div>
</body>
</html>

main/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SemWeb</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}
">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<script>
function collapseFeature() {
  var b1 = document.getElementById("feature");
  if(b1.style.display == "none"){
	b1.style.display = "block";
  }else{
	b1.style.display = "none";
	}
}
function collapseRating() {
  var b1 = document.getElementById("rating");
  if(b1.style.display == "none"){
	b1.style.display = "block";
  }else{
	b1.style.display = "none";
	}
}
function collapseComparison() {
  var b1 = document.getElementById("comparison");
  if(b1.style.display == "none"){
	b1.style.display = "block";
  }else{
	b1.style.display = "none";
	}
}
function collapseLocation() {
  var b1 = document.getElementById("location");
  if(b1.style.display == "none"){
	b1.style.display = "block";
  }else{
	b1.style.display = "none";
	}
}
</script>
<div class="container">
    <br>
    <div class="row height d-flex justify-content-center align-items-center">
        <div class="align-items-center">
			<form method="POST">
				{% csrf_token %}
				Sort By: {{ form.sortBy }} <br>
				Sort Options: {{ form.sortOptions }}
				<table>
				<tr style="background-color:coral;" onclick="collapseFeature()">
					<td><b>Hospital Feature</b><td style="align:right"><b><h3>➕</b></h3>
					<tr><td id="feature" style="display:block">
						<table>
						<tr><td colspan=2><b>Hospital Name</b>
						<tr><td colspan=2>{{form.name}}
						
						<tr><td colspan=2><b>Hospital Type</b>
						<tr><td colspan=2>{{form.type}}
						
						<tr><td colspan=2><b>ER availability</b>
						<tr><td>Yes<td>{{form.erYes}}
						<tr><td>No<td>{{ form.erNo }}
						
						<tr><td colspan=2><b>Hospital Ownership</b>
						<tr><td>Government<td>{{form.government}}
						<tr><td>Non-profit<td>{{ form.nonprofit }}
						<tr><td>Physician<td>{{ form.physician }}
						<tr><td>Proprietary<td>{{ form.proprietary }}
						<tr><td>Tribal<td>{{ form.tribal }}
						<tr>
						</table>
				<tr style="background-color:coral;" onclick="collapseLocation()">
					<td><b>Hospital Location</b><td style="align:right"><b><h3>➕</b></h3>
					<tr><td id="location" style="display:block">
						<table>
						<tr><td colspan=2><b>Hospital Address</b>
						<tr><td colspan=2>{{form.address}}
						
						<tr><td colspan=2><b>City</b>
						<tr><td colspan=2>{{form.city}}
						
						<tr><td colspan=2><b>Postal Code</b>
						<tr><td colspan=2>{{form.zip}}
						
						<tr><td colspan=2><b>County</b>
						<tr><td colspan=2>{{form.county}}
						
						<tr><td colspan=2><b>State</b>
						<tr><td colspan=2>{{form.state}}
						</table>
				 <tr style="background-color:coral;" onclick="collapseRating()">
					<td><b>Hospital Rating</b><td style="align:right"><b><h3>➕</b></h3>
					<tr><td id="rating" style="display:none">
						<table>
						<tr><td> Unknown <td> {{form.ratena}}
						<tr><td> ★ <td> {{form.rate1}}
						<tr><td> ★★ <td> {{form.rate2}}
						<tr><td> ★★★ <td> {{form.rate3}}
						<tr><td> ★★★★ <td> {{form.rate4}}
						<tr><td> ★★★★★ <td> {{form.rate5}}
						</table>
				<tr style="background-color:coral;" onclick="collapseComparison()">
					<td><b>Comparison</b><td style="align:right"><b><h3>➕</b></h3>
					<tr><td><table id="comparison" style="display:none">
						<tr><td colspan=2><b>Mortality Rate</b>
						<tr><td>Above national average <td>{{form.mortalityAbove}}
						<tr><td>Below national average <td>{{ form.mortalityBelow }}
						<tr><td>Equal to national average <td>{{ form.mortalityEqual }}
						<tr><td>Unknown <td>{{ form.mortalityNa }}
						
						<tr><td colspan=2><b>Mortality Rate</b>
						<tr><td>Above national average <td>{{form.mortalityAbove}}
						<tr><td>Below national average <td>{{ form.mortalityBelow }}
						<tr><td>Equal to national average <td>{{ form.mortalityEqual }}
						<tr><td>Unknown <td>{{ form.mortalityNa }}
						
						<tr><td colspan=2><b>Safety of Care</b>
						<tr><td>Above national average <td>{{form.safetyAbove}}
						<tr><td>Below national average <td>{{ form.safetyBelow }}
						<tr><td>Equal to national average <td>{{ form.safetyEqual }}
						<tr><td>Unknown <td>{{ form.safetyNa }}
						
						<tr><td colspan=2><b>Readmission Rate</b>
						<tr><td>Above national average <td>{{form.readmissionAbove}}
						<tr><td>Below national average <td>{{ form.readmissionBelow }}
						<tr><td>Equal to national average <td>{{ form.readmissionEqual }}
						<tr><td>Unknown <td>{{ form.readmissionNa }}
						
						<tr><td colspan=2><b>Patient Experience</b>
						<tr><td>Above national average <td>{{form.patientExperienceAbove}}
						<tr><td>Below national average <td>{{ form.patientExperienceBelow }}
						<tr><td>Equal to national average <td>{{ form.patientExperienceEqual }}
						<tr><td>Unknown <td>{{ form.patientExperienceNa }}
						
						<tr><td colspan=2><b>Effectiveness of Care</b>
						<tr><td>Above national average <td>{{form.effectivenessAbove}}
						<tr><td>Below national average <td>{{ form.effectivenessBelow }}
						<tr><td>Equal to national average <td>{{ form.effectivenessEqual }}
						<tr><td>Unknown <td>{{ form.effectivenessNa }}
						
						<tr><td colspan=2><b>Timeliness of Experience</b>
						<tr><td>Above national average <td>{{form.timelinessAbove}}
						<tr><td>Below national average <td>{{ form.timelinessBelow }}
						<tr><td>Equal to national average <td>{{ form.timelinessEqual }}
						<tr><td>Unknown <td>{{ form.timelinessNa }}
						
						<tr><td colspan=2><b>Efficient use of Medical Imaging</b>
						<tr><td>Above national average <td>{{form.medicalImagingAbove}}
						<tr><td>Below national average <td>{{ form.medicalImagingBelow }}
						<tr><td>Equal to national average <td>{{ form.medicalImagingEqual }}
						<tr><td>Unknown <td>{{ form.medicalImagingNa }}
					<td>
				</table>
				<button type="submit">Lakukan Query</button>
			</form>
			<for
        </div>
        <!--<div class="col-md-1">
            <button class="btn btn-primary" type="submit">Search</button>
        </div>-->
    </div>
    <br>
    
        <h6 class="card-header d-flex justify-content-center bg bg-info">
            Hasil Pencarian Hospital
        </h6>

        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Rating</th>
                    <th>Hospital Type</th>
					<th>Phone Number</th>
                    <th>City</th>
					<th>Postal Code</th>
                    <th>County</th>
					<th>ER</th>
                    <th>Mortality Comparison</th>
					<th>Ownership</th>
                    <th>State</th>
					<th>Detail</th>
					
                </tr>
                </thead>
                <tbody>
                {% for hospital in qres.results.bindings %}
                <tr>
                    <td>{{hospital.name.value}}</td>
                    <td>{{hospital.address.value}}</td>
                    <td>{{hospital.overallRating.value}}</td>
                    <td>{{hospital.hospitalType.value}}</td>
					<td>{{hospital.phoneNumber.value}}</td>
                    <td>{{hospital.city.value}}</td>
                    <td>{{hospital.postalCode.value}}</td>
                    <td>{{hospital.county.value}}</td>
					<td>{{hospital.emergencyService.value}}</td>
                    <td>{{hospital.mortalityComparison.value}}</td>
                    <td>{{hospital.ownership.value}}</td>
                    <td>{{hospital.state.value}}</td>
                    <td>
                        <a class="btn btn-dark" href="{% url 'main:detail' hospital.hospital.value %}">Detail</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    <br>
    <br>
</div>
</body>
</html>